<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Secure Your Account · ICGU</title>
    <link rel="stylesheet" href="{{ asset('css/staff-admin.css') }}">
</head>
<body class="login-page">
<div class="login-card" style="max-width:620px">
    <div class="brand-mark">ICGU</div>
    <span class="eyebrow">Secretariat security</span>
    <h1>Set up multi-factor authentication</h1>
    <p>Use Google Authenticator, Microsoft Authenticator, Authy, 1Password, or another TOTP-compatible authenticator.</p>

    @if($errors->any())
        <div class="notice error">{{ $errors->first() }}</div>
    @endif

    <div style="display:grid;gap:18px;justify-items:center;margin:22px 0">
        <div id="mfa-qr" aria-label="Authenticator QR code" style="background:#fff;padding:14px;border-radius:14px;min-width:248px;min-height:248px;display:grid;place-items:center"></div>
        <div style="text-align:left;width:100%;max-width:420px">
            <strong>On the staff member's phone:</strong>
            <ol style="margin:10px 0 0;padding-left:22px;line-height:1.7">
                <li>Open an authenticator app.</li>
                <li>Tap <strong>Add account</strong> or the <strong>+</strong> button.</li>
                <li>Choose <strong>Scan QR code</strong>.</li>
                <li>Scan the code above.</li>
                <li>Enter the 6-digit code generated by the app below.</li>
            </ol>
        </div>
    </div>

    <div id="qr-fallback" class="notice" hidden>
        The QR code could not be displayed. Use the manual setup key below instead.
    </div>

    <details style="margin:18px 0">
        <summary style="cursor:pointer;font-weight:700">Can't scan the QR code?</summary>
        <div class="notice" style="margin-top:12px">
            <strong>Manual setup key</strong><br>
            <code style="word-break:break-all">{{ $secret }}</code>
        </div>
        <p style="font-size:12px;margin-top:8px">Keep this setup key private. Anyone who has it can generate authenticator codes for this account.</p>
    </details>

    <form method="POST" action="{{ route('staff.mfa.confirm') }}">
        @csrf
        <div class="field">
            <label for="code">6-digit authenticator code</label>
            <input id="code" name="code" inputmode="numeric" autocomplete="one-time-code" maxlength="12" required autofocus>
        </div>
        <button class="btn btn-primary" type="submit">Verify and enable MFA</button>
    </form>

    <p style="font-size:12px;margin-top:20px">The MFA secret is encrypted in the ICGU database and is not displayed again after setup. Save the recovery codes shown after verification.</p>
</div>

<script
    src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"
    integrity="sha512-CNgIRecGo7nphbeZ04Sc13ka07paqdeTu0WR1IM4kNcpmBAUSHSQX0FslNhTDadL4O5SAGapGt4FodqL8My0mA=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"></script>
<script>
(() => {
    const container = document.getElementById('mfa-qr');
    const fallback = document.getElementById('qr-fallback');
    const provisioningUri = @json($provisioningUri);

    if (!container || typeof window.QRCode !== 'function') {
        if (fallback) fallback.hidden = false;
        return;
    }

    new QRCode(container, {
        text: provisioningUri,
        width: 220,
        height: 220,
        colorDark: '#071d49',
        colorLight: '#ffffff',
        correctLevel: QRCode.CorrectLevel.M,
    });
})();
</script>
</body>
</html>
