@extends('layouts.staff-admin')
@section('title',$member->registration_number)
@section('page-title','Member Record')
@section('content')
<div class="hero"><div style="display:flex;gap:18px;align-items:center">@if($member->profile_photo_path)<img src="{{ route('staff.members.photo',$member) }}" alt="{{ $member->display_name }}" style="width:88px;height:88px;border-radius:50%;object-fit:cover;border:3px solid rgba(255,255,255,.75)">@endif<div><span class="eyebrow">{{ $member->membershipPlan?->name ?? 'ICGU Membership' }} · Tier: {{ $member->membership_tier ?? 'Unassigned' }}</span><h2>{{ $member->display_name }}</h2><p>{{ $member->registration_number }} · Registered {{ $member->registration_date?->format('d M Y') }} @if($member->is_job_seeker) · <strong>Job seeker</strong>@endif</p></div></div><span class="status {{ $member->status?->code==='ACTIVE'?'ok':($member->status?->code==='EXPIRED'?'bad':'warn') }}">{{ $member->status?->code ?? '—' }}</span></div>
<div class="detail-grid section">
<section class="card"><div class="section-head"><h3>Member profile</h3></div><div class="meta"><div><span>Phone</span><strong>{{ $member->phone ?? '—' }}</strong></div><div><span>Primary email</span><strong>{{ $member->primaryEmail?->email ?? $member->emails->first()?->email ?? '—' }}</strong></div><div><span>Organisation</span><strong>{{ $member->organisation?->legal_name ?? $member->organization ?? '—' }}</strong></div><div><span>Job title</span><strong>{{ $member->job_title ?? '—' }}</strong></div><div><span>Membership tier</span><strong>{{ $member->membership_tier ?? 'Unassigned' }}</strong></div><div><span>Career availability</span><strong>{{ $member->is_job_seeker ? 'Seeking opportunities' : 'Not marked as job seeker' }}</strong></div>@if($member->cv_path && auth()->user()->hasPermission('documents.view'))<div><span>CV</span><strong><a href="{{ route('staff.members.cv',$member) }}">Download CV</a></strong></div>@endif @if(auth()->user()->hasPermission('finance.view'))<div><span>Outstanding balance</span><strong>UGX {{ number_format((float)$member->outstanding_balance,0) }}</strong></div>@endif @if(auth()->user()->hasPermission('portal.view'))<div><span>Current credential</span><strong>{{ ($member->activeCredential && $member->activeCredential->is_valid && $member->status?->code==='ACTIVE') ? ucfirst($member->activeCredential->credential_type) : 'None current' }}</strong></div>@endif</div></section>
<section class="card"><div class="section-head"><h3>Membership periods</h3></div>@if($member->periods->isEmpty())<div class="empty">No membership periods recorded.</div>@else<div class="table-wrap"><table class="table"><thead><tr><th>Year</th><th>Coverage</th><th>Flags</th></tr></thead><tbody>@foreach($member->periods as $period)<tr><td>{{ $period->target_year }}</td><td>{{ $period->start_date->format('d M Y') }} – {{ $period->end_date->format('d M Y') }}</td><td>@if($period->is_backdated)<span class="status warn">Backdated</span>@endif @if($period->is_future)<span class="status info">Future</span>@endif</td></tr>@endforeach</tbody></table></div>@endif</section>
</div>

@if(auth()->user()->hasPermission('members.manage'))
<section class="section card"><div class="section-head"><div><h3>Profile photo, tier & career</h3><p>Maintain the real member photo and optional job-seeker CV after manual or CSV onboarding.</p></div></div><form method="POST" action="{{ route('staff.members.profile-assets',$member) }}" enctype="multipart/form-data">@csrf @method('PATCH')<div class="grid grid-2"><div class="field"><label>Membership tier</label><input name="membership_tier" value="{{ old('membership_tier',$member->membership_tier) }}" placeholder="ICGU tier/level"></div><div class="field"><label>Replace profile photo</label><input name="profile_photo" type="file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG or WebP, maximum 5 MB.</small></div><div><label style="display:flex;gap:10px;align-items:center;margin:10px 0"><input type="checkbox" name="is_job_seeker" value="1" @checked(old('is_job_seeker',$member->is_job_seeker))> <strong>Seeking employment / professional opportunities</strong></label></div><div class="field"><label>{{ $member->cv_path ? 'Replace CV' : 'Upload CV' }}</label><input name="cv" type="file" accept=".pdf,.doc,.docx"><small>Required when first marking a member as a job seeker. Maximum 10 MB.</small></div></div><div class="actions"><button class="btn btn-primary" type="submit">Save profile & career details</button></div></form></section>
@endif

@if(auth()->user()->hasPermission('renewals.view'))
<section class="section card"><div class="section-head"><div><h3>Renewal history</h3><p>Annual billing and coverage lifecycle.</p></div>@if(auth()->user()->hasPermission('renewals.manage'))<form method="POST" action="{{ route('staff.members.renew',$member) }}">@csrf<button class="btn btn-accent" type="submit">Prepare next renewal</button></form>@endif</div>@if($member->renewals->isEmpty())<div class="empty">No formal renewal cycles recorded yet.</div>@else<div class="table-wrap"><table class="table"><thead><tr><th>Year</th><th>Status</th><th>Invoice</th>@if(auth()->user()->hasPermission('finance.view'))<th>Balance</th>@endif<th>Coverage</th><th>Payment action</th></tr></thead><tbody>@foreach($member->renewals as $renewal)<tr><td>{{ $renewal->target_year }}</td><td><span class="status {{ $renewal->status==='activated'?'ok':($renewal->status==='partial'?'warn':'info') }}">{{ $renewal->status }}</span></td><td>{{ $renewal->invoice?->invoice_number ?? '—' }}</td>@if(auth()->user()->hasPermission('finance.view'))<td class="money">UGX {{ number_format((float)$renewal->balance_due,0) }}</td>@endif<td>{{ $renewal->resultingPeriod ? $renewal->resultingPeriod->start_date->format('d M Y').' – '.$renewal->resultingPeriod->end_date->format('d M Y') : 'Pending' }}</td><td>@if(auth()->user()->hasPermission('renewals.manage') && $renewal->invoice && !$renewal->invoice->is_fully_settled)<details><summary class="btn btn-soft">Record payment</summary><form style="margin-top:10px" method="POST" action="{{ route('staff.renewals.payment',[$member,$renewal]) }}">@csrf<div class="field"><label>Amount</label><input name="amount" type="number" min="1" max="{{ (float)$renewal->balance_due }}" required></div><div class="field"><label>Method</label><select name="payment_method">@foreach(['bank_transfer','mobile_money','cash','card','cheque','other'] as $method)<option value="{{ $method }}">{{ ucwords(str_replace('_',' ',$method)) }}</option>@endforeach</select></div><div class="field"><label>Transaction reference</label><input name="transaction_reference" required></div><div class="field"><label>Provider</label><input name="payment_provider"></div><div class="actions"><button class="btn btn-primary" type="submit">Post payment</button></div></form></details>@else—@endif</td></tr>@endforeach</tbody></table></div>@endif</section>
@endif

@if(auth()->user()->hasPermission('portal.view'))
<section class="section card"><div class="section-head"><div><h3>Portal access</h3><p>Authorised member self-service accounts and pending invitations.</p></div></div><div class="grid grid-2"><div><h4>Linked accounts</h4>@if($member->portalAccounts->isEmpty())<div class="empty">No portal accounts linked.</div>@else<div class="table-wrap"><table class="table"><thead><tr><th>User</th><th>Access</th><th>Linked</th></tr></thead><tbody>@foreach($member->portalAccounts as $account)<tr><td>{{ $account->user?->name }}<br><small>{{ $account->user?->email }}</small></td><td><span class="status info">{{ $account->access_role }}</span></td><td>{{ $account->linked_at?->format('d M Y') }}</td></tr>@endforeach</tbody></table></div>@endif</div>
<div>@if(auth()->user()->hasPermission('portal.manage'))<h4>Issue invitation</h4><form method="POST" action="{{ route('staff.members.invite',$member) }}">@csrf<div class="field"><label>Email</label><input type="email" name="email" required></div><div class="field"><label>Access role</label><select name="access_role">@if($member->type==='individual')<option value="owner">Owner</option>@else<option value="representative">Representative</option><option value="billing">Billing</option><option value="owner">Owner</option>@endif</select></div><div class="actions"><button class="btn btn-primary" type="submit">Create secure invitation</button></div></form>@endif</div></div></section>
@endif

@if(auth()->user()->hasPermission('finance.view'))
<section class="section"><div class="section-head"><h3>Financial ledger</h3></div><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Type</th><th>Document/reference</th><th>Amount</th><th>Balance</th></tr></thead><tbody>@foreach($member->invoices->concat($member->payments)->sortByDesc('created_at') as $entry)<tr><td>{{ $entry->created_at?->format('d M Y') }}</td><td><span class="status {{ $entry->type==='payment'?'ok':'info' }}">{{ $entry->type }}</span></td><td class="mono">{{ $entry->invoice_number ?? $entry->tx_reference ?? '—' }}</td><td class="money">UGX {{ number_format((float)$entry->amount,0) }}</td><td class="money">{{ $entry->type==='invoice' ? 'UGX '.number_format((float)$entry->balance_due,0) : '—' }}</td></tr>@endforeach</tbody></table></div></section>
@endif
@endsection
