@extends('layouts.staff-admin')
@section('title','Application '.$application->reference)
@section('page-title','Application Review')
@section('content')
@php($applicant=$application->organisation?->legal_name ?: trim(($application->first_name ?? '').' '.($application->last_name ?? '')))
<div class="hero"><div><span class="eyebrow mono">{{ $application->reference }}</span><h2>{{ $applicant ?: $application->email }}</h2><p>{{ $application->plan?->name }} · Submitted {{ $application->submitted_at?->format('d M Y H:i') ?? 'not yet' }}</p></div><span class="status {{ $application->status==='admitted'?'ok':($application->status==='rejected'?'bad':($application->status==='approved_pending_payment'?'warn':'info')) }}">{{ str_replace('_',' ',$application->status) }}</span></div>
<div class="detail-grid section">
<section class="card"><div class="section-head"><h3>Applicant record</h3></div><div class="meta"><div><span>Email</span><strong>{{ $application->email }}</strong></div><div><span>Phone</span><strong>{{ $application->phone ?? '—' }}</strong></div><div><span>Job title</span><strong>{{ $application->job_title ?? '—' }}</strong></div><div><span>Institution</span><strong>{{ $application->institution_name ?? $application->organisation?->legal_name ?? '—' }}</strong></div><div><span>Integrity declaration</span><strong>{{ $application->integrity_declaration_at ? 'Completed' : 'Pending' }}</strong></div><div><span>Terms accepted</span><strong>{{ $application->terms_accepted_at ? 'Yes' : 'No' }}</strong></div></div>@if($application->applicant_notes)<p>{{ $application->applicant_notes }}</p>@endif</section>
<section class="card"><div class="section-head"><h3>Decision & billing</h3></div><div class="meta"><div><span>Decision by</span><strong>{{ $application->decisionMaker?->name ?? '—' }}</strong></div><div><span>Decision date</span><strong>{{ $application->decided_at?->format('d M Y H:i') ?? '—' }}</strong></div><div><span>Invoice</span><strong>{{ $application->invoice?->invoice_number ?? 'Not issued' }}</strong></div><div><span>Balance</span><strong>{{ $application->invoice ? 'UGX '.number_format((float)$application->invoice->balance_due,0) : '—' }}</strong></div></div>@if($application->decision_notes)<p><strong>Decision notes:</strong> {{ $application->decision_notes }}</p>@endif @if($application->resultingMember)<div class="actions"><a class="btn btn-primary" href="{{ route('staff.members.show',$application->resultingMember) }}">Open member record</a></div>@endif</section>
</div>

<section class="section card"><div class="section-head"><div><h3>Documents</h3><p>Uploaded evidence attached to this application.</p></div></div>@if($application->documents->isEmpty())<div class="empty">No documents uploaded.</div>@else<div class="table-wrap"><table class="table"><thead><tr><th>Type</th><th>File</th><th>Size</th><th>Verified</th><th></th></tr></thead><tbody>@foreach($application->documents as $document)<tr><td>{{ ucwords(str_replace('_',' ',$document->document_type)) }}</td><td>{{ $document->original_name }}</td><td>{{ number_format($document->size_bytes/1024,0) }} KB</td><td>{{ $document->verified_at?->format('d M Y') ?? 'Not verified' }}</td><td>@if(auth()->user()->hasPermission('documents.view'))<a class="btn btn-soft" href="{{ url('/staff/membership/documents/'.$document->id.'/download') }}">Download</a>@endif</td></tr>@endforeach</tbody></table></div>@endif</section>

@if($application->representatives->isNotEmpty())<section class="section card"><div class="section-head"><h3>Corporate representatives</h3></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Position</th><th>Email</th><th>Phone</th></tr></thead><tbody>@foreach($application->representatives as $rep)<tr><td>{{ trim(($rep->title ? $rep->title.' ' : '').$rep->first_name.' '.$rep->last_name) }} @if($rep->is_primary)<span class="status info">Primary</span>@endif</td><td>{{ $rep->position ?? '—' }}</td><td>{{ $rep->email }}</td><td>{{ $rep->phone ?? '—' }}</td></tr>@endforeach</tbody></table></div></section>@endif

@if(auth()->user()->hasPermission('applications.review') && in_array($application->status,['submitted','under_review'],true))
<section class="section card"><div class="section-head"><div><h3>Review decision</h3><p>Decisions are permanently recorded in the audit trail.</p></div></div><div class="grid grid-2">
@if($application->status==='submitted')<form method="POST" action="{{ route('staff.applications.review',$application->reference) }}">@csrf<button class="btn btn-primary" type="submit">Start formal review</button></form>@endif
<form method="POST" action="{{ route('staff.applications.approve',$application->reference) }}">@csrf<div class="field"><label for="notes">Approval notes</label><textarea id="notes" name="notes" placeholder="Optional committee/review notes"></textarea></div><div class="actions"><button class="btn btn-accent" type="submit">Approve pending payment</button></div></form>
<form method="POST" action="{{ route('staff.applications.reject',$application->reference) }}">@csrf<div class="field"><label for="reason">Rejection reason</label><textarea id="reason" name="reason" required minlength="10" placeholder="Required reason for the decision"></textarea></div><div class="actions"><button class="btn btn-danger" type="submit">Reject application</button></div></form>
</div></section>
@endif

@if($application->invoice)
<section class="section card"><div class="section-head"><div><h3>Invoice & payments</h3><p>{{ $application->invoice->invoice_number }} · UGX {{ number_format((float)$application->invoice->amount,0) }}</p></div><span class="status {{ $application->invoice->is_fully_settled?'ok':($application->invoice->is_overdue?'bad':'warn') }}">UGX {{ number_format((float)$application->invoice->balance_due,0) }} balance</span></div>
@if($application->payments->isNotEmpty())<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Reference</th><th>Method</th><th>Amount</th><th>Receipt</th></tr></thead><tbody>@foreach($application->payments as $payment)<tr><td>{{ ($payment->received_at ?? $payment->created_at)?->format('d M Y') }}</td><td class="mono">{{ $payment->tx_reference }}</td><td>{{ ucwords(str_replace('_',' ',$payment->payment_method ?? 'payment')) }}</td><td class="money">UGX {{ number_format((float)$payment->amount,0) }}</td><td>@if($payment->receipt)<a href="{{ route('staff.receipts.show',$payment->receipt) }}">{{ $payment->receipt->receipt_number }}</a>@else—@endif</td></tr>@endforeach</tbody></table></div>@endif
@if(auth()->user()->hasPermission('finance.manage') && !$application->invoice->is_fully_settled)<form class="section" method="POST" action="{{ route('staff.applications.payment',$application->reference) }}">@csrf<input type="hidden" name="invoice_id" value="{{ $application->invoice->id }}"><div class="form-grid"><div class="field"><label>Amount (UGX)</label><input name="amount" type="number" min="1" max="{{ (float)$application->invoice->balance_due }}" required></div><div class="field"><label>Payment method</label><select name="payment_method" required>@foreach(['bank_transfer','mobile_money','cash','card','cheque','other'] as $method)<option value="{{ $method }}">{{ ucwords(str_replace('_',' ',$method)) }}</option>@endforeach</select></div><div class="field"><label>Transaction reference</label><input name="transaction_reference" required maxlength="100"></div><div class="field"><label>Provider / bank</label><input name="payment_provider" maxlength="80"></div><div class="field"><label>Received at</label><input name="received_at" type="datetime-local"></div></div><div class="actions"><button class="btn btn-primary" type="submit">Record payment & issue receipt</button></div></form>@endif
@if(auth()->user()->hasPermission('applications.admit') && $application->status==='approved_pending_payment' && $application->invoice->is_fully_settled)<form class="section" method="POST" action="{{ route('staff.applications.admit',$application->reference) }}">@csrf<button class="btn btn-accent" type="submit">Admit as active ICGU member</button></form>@endif
</section>
@endif
@endsection
